package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SellerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAllPropertiesEquals(Seller expected, Seller actual) {
        assertSellerAutoGeneratedPropertiesEquals(expected, actual);
        assertSellerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAllUpdatablePropertiesEquals(Seller expected, Seller actual) {
        assertSellerUpdatableFieldsEquals(expected, actual);
        assertSellerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerAutoGeneratedPropertiesEquals(Seller expected, Seller actual) {
        assertThat(expected)
            .as("Verify Seller auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerUpdatableFieldsEquals(Seller expected, Seller actual) {
        assertThat(expected)
            .as("Verify Seller relevant properties")
            .satisfies(e -> assertThat(e.getSellerName()).as("check sellerName").isEqualTo(actual.getSellerName()))
            .satisfies(e -> assertThat(e.getState()).as("check state").isEqualTo(actual.getState()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSellerUpdatableRelationshipsEquals(Seller expected, Seller actual) {
        assertThat(expected)
            .as("Verify Seller relationships")
            .satisfies(e -> assertThat(e.getProducerId()).as("check producerId").isEqualTo(actual.getProducerId()))
            .satisfies(e -> assertThat(e.getSellerInfoId()).as("check sellerInfoId").isEqualTo(actual.getSellerInfoId()));
    }
}
